name: Run Duster

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  duster:
    name: Duster
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
          php-version: 8.0
          extensions: posix, dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

    - name: Install dependencies
      run: composer install --prefer-source --no-interaction

    - name: Run Duster
      run: composer lint
