name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  tests:
    name: Tests (PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }})
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
        php-versions: ['8.2']

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
          php-version: ${{ matrix.php-versions }}
          extensions: posix, dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, fileinfo, sodium
          coverage: none

    - name: Copy .env
      run: cp .env.example .env

    - name: Install Composer Dependencies
      run: |
        composer remove laravel/nova --no-scripts --no-interaction

    - name: Install Frontend Dependencies
      run: npm install

    - name: Build Assets
      run: npm run build

    - name: Generate Key
      run: export APP_ENV=testing && php artisan key:generate
      shell: bash

    - name: Run PHP Tests
      run: ./vendor/bin/pest
